const httpStatus = {
  100: 'Continuar. O servidor recebeu a solicitação e o cliente pode continuar com a solicitação.',
  101: 'Mudando Protocolos. O servidor concorda em mudar o protocolo solicitado pelo cliente.',
  200: 'OK. A solicitação foi bem-sucedida.',
  201: 'Criado. A solicitação foi bem-sucedida e um novo recurso foi criado como resultado.',
  202: 'Aceito. A solicitação foi aceita para processamento, mas pode não ter sido concluída.',
  203: 'Informações Não Autoritativas. A resposta é uma representação do recurso solicitado, mas pode originar-se de outra fonte.',
  204: 'Sem Conteúdo. A resposta não contém nenhum conteúdo (como no caso de uma solicitação de sucesso DELETE).',
  205: 'Conteúdo Resetado. A resposta requer que o cliente redefina o documento do qual a solicitação foi originada.',
  206: 'Conteúdo Parcial. A resposta contém apenas uma parte do recurso solicitado.',
  300: 'Múltipla Escolha. A solicitação tem várias opções para o recurso solicitado.',
  301: 'Movido Permanentemente. O recurso solicitado foi permanentemente movido para uma nova localização.',
  302: 'Encontrado. O recurso solicitado foi encontrado em uma nova localização temporária.',
  303: 'Veja Outro. A resposta à solicitação pode ser encontrada em outro local.',
  304: 'Não Modificado. O recurso não foi modificado desde a última solicitação.',
  305: 'Use Proxy. O cliente deve usar o proxy fornecido.',
  307: 'Redirecionamento Temporário. A solicitação deve ser reenviada para outra URL temporariamente.',
  308: 'Redirecionamento Permanente. A solicitação e todos os futuros acessos devem ser repetidos usando outra URL.',
  400: 'Requisição inválida. Por favor, verifique os dados enviados.',
  401: 'Não autorizado. Por favor, faça login para acessar esta página.',
  403: 'Acesso proibido. Você não tem permissão para acessar esta página.',
  404: 'Página não encontrada. A URL solicitada não existe.',
  405: 'Método não permitido. O método HTTP usado não é suportado para esta rota.',
  408: 'Tempo limite de solicitação excedido. Por favor, tente novamente mais tarde.',
  409: 'Conflito. A solicitação não pôde ser concluída devido a um conflito com o estado atual do recurso.',
  410: 'Recurso não disponível. O recurso solicitado não está mais disponível e não será mais acessível.',
  418: 'Sou um bule de chá. Esta solicitação foi recusada porque o servidor é um bule de chá.',
  429: 'Muitas solicitações. Limite de taxa excedido. Tente novamente mais tarde.',
  500: 'Erro interno do servidor. Por favor, tente novamente mais tarde.',
  501: 'Não implementado. O servidor não suporta a funcionalidade necessária para atender à solicitação.',
  502: 'Gateway Ruim. O servidor recebeu uma resposta inválida do servidor upstream ao tentar atender à solicitação.',
  503: 'Serviço Indisponível. O servidor está atualmente indisponível devido a sobrecarga temporária ou manutenção programada.',
  504: 'Tempo limite do Gateway. O servidor não recebeu uma resposta oportuna do servidor upstream enquanto aguardava a conclusão da solicitação.',
  505: 'Versão HTTP não suportada. A versão do protocolo HTTP usado na solicitação não é suportada pelo servidor.',
  };
  
export default httpStatus;